**Why is NumPy Faster Than Lists?**  
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called the locality of reference in computer science. This is the main reason why NumPy is faster than lists. Also, it is optimized to work with the latest CPU architectures.

**Which Language is NumPy Written In?**  
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.  


In [10]:
import numpy as np

print(np.__version__)

1.23.5


NumPy is used to work with arrays. The array object in NumPy is called ndarray.  
We can create a NumPy `ndarray` object by using the `array()` function.

To create an `ndarray`, we can pass a list, tuple or any array-like object into the `array()` method, and it will be converted into an ndarray:  

In [12]:
arr = numpy.array([1, 2, 3, 4, 5])
print(type(arr))
print('list to ndarray',arr)

arr = np.array((1, 2, 3, 4, 5))
print('tuple to ndarray',arr)

<class 'numpy.ndarray'>
list to ndarray [1 2 3 4 5]
tuple to ndarray [1 2 3 4 5]


**Dimensions in Arrays**  
A dimension in arrays is one level of array depth (nested arrays).  
**nested array: are arrays that have arrays as their elements.**

**Access Array Elements**
Array indexing is the same as accessing an array element.  
Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.  
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.



In [20]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim, a)
print(b.ndim, b)
print(c.ndim, c)
print(d.ndim, d)


print(b[2] + b[3])
print(c[1, 2])
print(d[0, 1, 2])

print('Last element from 2nd dim: ', c[1, -1])


0 42
1 [1 2 3 4 5]
2 [[1 2 3]
 [4 5 6]]
3 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
7
6
6
Last element from 2nd dim:  6


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

In [16]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


**Slicing arrays**
Slicing in python means taking elements from one given index to another given index.  

We pass slice instead of index like this: [start:end].  

We can also define the step, like this: [start:end:step].  

If we don't pass start its considered 0  
If we don't pass end its considered length of array in that dimension  
If we don't pass step its considered 1  

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])# end is excluded
print(arr[4:])
print(arr[-3:-1])#Slice from the index 3 from the end to index 1 from the end


print(arr[1:5:2])#every second element(step)
print(arr[::2])#return every 2nd element than 

#slice 2-D arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2]) #take dimension=0,1 and give 2nd index element which is 3,8
print(arr[0:2, 1:4])

[2 3 4 5]
[5 6 7]
[5 6]
[2 4]
[1 3 5 7]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


**Data Types in NumPy**  
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer  
b - boolean  
u - unsigned integer  
f - float  
c - complex float  
m - timedelta  
M - datetime  
O - object  
S - string  
U - unicode string  
V - fixed chunk of memory for other type ( void )  

We use the `array()` function to create arrays, this function can take an optional argument: `dtype` that allows us to define the expected data type of the array elements  

**Converting Data Type on Existing Arrays**
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.  
The `astype()` function creates a copy of the array, and allows you to specify the data type as a parameter.
The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [45]:
arr = np.array([1, 2, 3, 4,5], dtype='S')
print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4,5])
print(arr.dtype)

newarr = arr.astype('U')
print(newarr)
print(newarr.dtype)

newarr = arr.astype('f')
print(newarr)
print(newarr.dtype)

newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)



arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)



[b'1' b'2' b'3' b'4' b'4']
|S1
int32
['1' '2' '3' '4' '5']
<U11
[1. 2. 3. 4. 5.]
float32
[ True  True  True  True  True]
bool
<U6


**The Difference Between Copy and View**  
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

  The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

  The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.


**Check if Array Owns its Data**  
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns `None` if the array owns the data.

Otherwise, the `base`  attribute refers to the original object.

The copy returns `None.`
The view returns the original array.

In [51]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

arr[0] = 42
print(arr)
print(x)

arr[0] = 31
print(arr)
print(y)

print(x.base)
print(y.base)

[42  2  3  4  5]
[1 2 3 4 5]
[31  2  3  4  5]
[31  2  3  4  5]
None
[31  2  3  4  5]


**Get the Shape of an Array**  
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.   
**What does the shape tuple represent?**
Integers at every index tells about the number of elements the corresponding dimension has.
In the example at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.

In [53]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)


arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


**Reshaping arrays**
Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
print(newarr.shape)


newarr = arr.reshape(2, 3, 2)
print(newarr)
print(newarr.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


**Unknown Dimension**
You are allowed to have one "unknown" dimension.
Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
Pass -1 as the value, and NumPy will calculate this number for you.

Note: We can not pass -1 to more than one dimension.

In [59]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Flattening the arrays**
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [60]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


**The function nditer()** is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

**Iterating on Each Scalar Element**
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

**Enumeration:** mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [74]:

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)
for x in arr:
  for y in x:
    for z in y:
      print(z)

for x in np.nditer(arr):
  print(x)

for x in np.nditer(arr[:, ::2]):
  print(x)


for idx, x in np.ndenumerate(arr):
  print(idx, x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8
1
2
5
6
(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


We pass a sequence of arrays that we want to join to the `concatenate()` function, along with the axis. If axis is not explicitly passed, it is taken as 0.

**Joining Arrays Using Stack Functions**
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [69]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)


arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)


arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)
arr = np.hstack((arr1, arr2))
print(arr)
arr = np.vstack((arr1, arr2))
print(arr)

arr = np.dstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


**Splitting NumPy Arrays**
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use **array_split()** for splitting arrays, we pass it the array we want to split and the number of splits.

Note: The return value is a list containing three arrays.

If the array has less elements than required, it will adjust from the end accordingly.

**Note**: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.


In [75]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 7)
print(newarr)

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


**To search an array, use the where() method.**

You can search an array for a certain value, and return the indexes that get a match.

There is a method called `searchsorted()` which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The `searchsorted()` method is assumed to be used on sorted arrays.


In [77]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
print(x)

x = np.where(arr%2 == 0)
print(x)


arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)
print(x)

x = np.searchsorted(arr, 7, side='right')
print(x)

x = np.searchsorted(arr, [2, 4, 6])
print(x)

(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)
1
2
[0 0 0]
